export const Colors = {
  primary: '#1E40AF',
  primaryLight: '#E0F2FE',
  accent: '#3B82F6',
  background: '#FFFFFF',
  surface: '#F9FAFB',
  textPrimary: '#1F2937',
  textSecondary: '#6B7280',
  textMuted: '#9CA3AF',
  border: '#E5E7EB',
  borderLight: '#F3F4F6',
  success: '#16A34A',
  successLight: '#DCFCE7',
  warning: '#F59E0B',
  warningLight: '#FEF3C7',
  error: '#DC2626',
  errorLight: '#FEE2E2',
  white: '#FFFFFF',
  black: '#000000',
  overlay: 'rgba(0, 0, 0, 0.5)',
  shadow: 'rgba(0, 0, 0, 0.08)',
  cardBackground: '#FFFFFF',
  inputBackground: '#F9FAFB',
  tabBarBackground: '#FFFFFF',
  tabBarActive: '#1E40AF',
  tabBarInactive: '#9CA3AF',
} as const;

export type ColorKey = keyof typeof Colors;
